name: Matrix
on: pull_request

jobs:
  node-version:
    runs-on: ${{ matrix. os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node_version: [12, 14, 16]
        exclude:
          - os: macos-latest
            node_version: 12
          - os: macos-latest
            node_version: 14
          - os: ubuntu-latest
            node_version: 16
      fail-fast: true
    steps:
      - name: Log matrix starting information
        run: |
          echo "Node version setting: ${{ matrix.node_version}}"
          echo "OS setting: ${{ matrix.os}}"
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v
